name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "be-nc-games"
          postgresql user: "kirsty"
          postgresql password: "ninja007"

      - name: test everything
        run: PGDATABASE=be-nc-games PGUSER=kirsty PGPASSWORD=ninja007 npm t
